/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an investor or seller account */
    post: operations['signup_api_auth_signup_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log in; returns access + refresh tokens */
    post: operations['login_api_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange a refresh token for a new token pair */
    post: operations['refresh_api_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user profile */
    get: operations['me_api_users_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/kyc/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mock KYC (توقيعك) for investors */
    post: operations['kyc_verify_investor_api_kyc_verify_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/kyc/seller': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mock KYC (توقيعك) for sellers */
    post: operations['kyc_verify_seller_api_kyc_seller_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/market/prices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Latest gold prices (all karats) + USD/IQD, served from the internal cache */
    get: operations['prices_api_market_prices_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/market/prices/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Downsampled price history for charts */
    get: operations['price_history_api_market_prices_history_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/listings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Browse listings (public). seller_id=me lists the caller's own listings. */
    get: operations['browse_listings_api_listings_get'];
    put?: never;
    /** Create a listing (seller, KYC required; price computed server-side) */
    post: operations['create_listing_api_listings_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/listings/{listing_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listing detail (public) */
    get: operations['get_listing_api_listings__listing_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Suspend / re-activate a listing (owner only). There is no delete. */
    patch: operations['update_listing_api_listings__listing_id__patch'];
    trace?: never;
  };
  '/api/listings/{listing_id}/promote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pay the fixed promotion fee (internal mock payment) and promote the listing */
    post: operations['promote_listing_api_listings__listing_id__promote_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ai/match': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Smart matching (free): budget → ranked listings; risk profile read from account */
    post: operations['smart_match_api_ai_match_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ai/risk-analysis': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pre-checkout risk insight (never blocks checkout) */
    post: operations['risk_analysis_api_ai_risk_analysis_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ai/insights': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Premium insights: alerts, market trend, portfolio performance */
    get: operations['premium_insights_api_ai_insights_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/transactions/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Price breakdown + signed quote + AI risk insight. Read-only (no reservation). */
    post: operations['preview_api_transactions_preview_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/transactions/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Execute the purchase atomically (KYC required; row-locked) */
    post: operations['confirm_api_transactions_confirm_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My transactions (investor: purchases; seller: sales on my listings) */
    get: operations['list_transactions_api_transactions_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/transactions/{transaction_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One transaction (parties only) */
    get: operations['get_transaction_api_transactions__transaction_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/subscription/subscribe': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Buy / renew Premium for 30 days (internal mock payment; no KYC needed) */
    post: operations['subscribe_api_subscription_subscribe_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/subscription/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current subscription tier and expiry */
    get: operations['subscription_status_api_subscription_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ownership/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verified gold balance (signature checked before returning) */
    get: operations['my_ownership_api_ownership_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** DB + price cache health */
    get: operations['health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Server-side business values the UI displays (fees, tiers). Read-only. */
    get: operations['public_config_api_config_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CommissionTier */
    CommissionTier: {
      /** Label */
      label: string;
      /** Min Grams */
      min_grams: string | null;
      /** Max Grams */
      max_grams: string | null;
      /** Rate */
      rate: string;
    };
    /** ConfirmIn */
    ConfirmIn: {
      /**
       * Asset Id
       * Format: uuid
       */
      asset_id: string;
      /**
       * Purchased Weight Grams
       * @example 84.250
       */
      purchased_weight_grams: number | string;
      /**
       * Quote Token
       * @description From the preview
       */
      quote_token: string;
    };
    /** ConfirmOut */
    ConfirmOut: {
      transaction: components['schemas']['TransactionOut'];
      ownership: components['schemas']['OwnershipSummary'];
      /** Listing Status */
      listing_status: string;
      /** Listing Available Weight Grams */
      listing_available_weight_grams: string;
      /**
       * Idempotent Replay
       * @default false
       */
      idempotent_replay: boolean;
    };
    /**
     * ErrorResponse
     * @description Body of every non-2xx response.
     */
    ErrorResponse: {
      /** Error Code */
      error_code: string;
      /** Message */
      message: string;
      /** Status */
      status: number;
      /** Details */
      details?: components['schemas']['FieldError'][] | null;
    };
    /** FieldError */
    FieldError: {
      /** Field */
      field: string;
      /** Message */
      message: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthOut */
    HealthOut: {
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded';
      /**
       * Database
       * @enum {string}
       */
      database: 'ok' | 'error';
      /** Price Cache Age Seconds */
      price_cache_age_seconds: number | null;
      /** Price Source */
      price_source: string | null;
      /** Price Is Stale */
      price_is_stale: boolean | null;
      /**
       * Time
       * Format: date-time
       */
      time: string;
    };
    /** InsightsOut */
    InsightsOut: {
      /**
       * Engine
       * @enum {string}
       */
      engine: 'rules' | 'llm';
      /** Alerts */
      alerts: string[];
      market: components['schemas']['MarketTrend'];
      portfolio: components['schemas']['PortfolioPerformance'];
    };
    /** KaratHolding */
    KaratHolding: {
      /** Karat */
      karat: number;
      /** Grams */
      grams: string;
      /** Current Value Iqd */
      current_value_iqd: string;
    };
    /** KaratPrice */
    KaratPrice: {
      /** Karat */
      karat: number;
      /** Price Per Gram Iqd */
      price_per_gram_iqd: string;
      /** Price Per Gram Usd */
      price_per_gram_usd: string;
    };
    /** KycOut */
    KycOut: {
      /** Kyc Verified */
      kyc_verified: boolean;
      /** Message */
      message: string;
      user: components['schemas']['UserOut'];
    };
    /**
     * ListingCreateIn
     * @description The price is computed server-side from the live 24K price; any price field is ignored.
     */
    ListingCreateIn: {
      /**
       * Total Weight Grams
       * @example 84.250
       */
      total_weight_grams: number | string;
      /**
       * Karat
       * @example 21
       * @enum {integer}
       */
      karat: 18 | 21 | 22 | 24;
    };
    /** ListingOut */
    ListingOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Seller Id
       * Format: uuid
       */
      seller_id: string;
      /** Seller Name */
      seller_name: string;
      /** Seller Kyc Verified */
      seller_kyc_verified: boolean;
      /** Karat */
      karat: number;
      /** Total Weight Grams */
      total_weight_grams: string;
      /** Available Weight Grams */
      available_weight_grams: string;
      /**
       * Base Price Per Gram
       * @description Reference price fixed at creation
       */
      base_price_per_gram: string;
      /**
       * Current Price Per Gram
       * @description Live price for this karat now; the purchase uses this (see preview)
       */
      current_price_per_gram: string | null;
      status: components['schemas']['ListingStatus'];
      /**
       * Is Promoted
       * @description Effective: is_promoted AND promotion_expiry_date > now
       */
      is_promoted: boolean;
      /** Promotion Expiry Date */
      promotion_expiry_date: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ListingStatus
     * @enum {string}
     */
    ListingStatus: 'active' | 'sold_out' | 'suspended';
    /** ListingStatusIn */
    ListingStatusIn: {
      /**
       * Status
       * @description Owner can suspend or re-activate. sold_out is set by the system only.
       * @enum {string}
       */
      status: 'active' | 'suspended';
    };
    /** LoginIn */
    LoginIn: {
      /**
       * Email
       * Format: email
       * @example zainab@example.iq
       */
      email: string;
      /**
       * Password
       * @example Sila@2026
       */
      password: string;
    };
    /** LoginOut */
    LoginOut: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      /**
       * Expires In
       * @description Access token lifetime in seconds
       */
      expires_in: number;
      user: components['schemas']['UserOut'];
    };
    /** MarketPricesOut */
    MarketPricesOut: {
      /**
       * Base Currency
       * @default IQD
       */
      base_currency: string;
      /**
       * Karats
       * @description 24, 22, 21, 18 (price = 24K × karat / 24)
       */
      karats: components['schemas']['KaratPrice'][];
      /**
       * Usd Iqd
       * @description 1 USD in IQD
       */
      usd_iqd: string;
      /**
       * Xau Usd Per Ounce
       * @description Global gold reference, USD per troy ounce
       */
      xau_usd_per_ounce: string;
      /**
       * Change 24H Pct
       * @description 24K change vs ~24h ago, percent (2 dp)
       */
      change_24h_pct: string | null;
      /**
       * Updated At
       * Format: date-time
       * @description When this price was fetched from the provider
       */
      updated_at: string;
      /**
       * Source
       * @description live | fallback | seed
       */
      source: string;
      /**
       * Is Stale
       * @description True when the last successful refresh is too old
       */
      is_stale: boolean;
    };
    /** MarketTrend */
    MarketTrend: {
      /** Price 24K Per Gram */
      price_24k_per_gram: string;
      /** Change 24H Pct */
      change_24h_pct: string | null;
      /** Change 7D Pct */
      change_7d_pct: string | null;
      /** Change 30D Pct */
      change_30d_pct: string | null;
      /** High 7D */
      high_7d: string | null;
      /** Low 7D */
      low_7d: string | null;
      /**
       * Trend
       * @enum {string}
       */
      trend: 'up' | 'down' | 'flat';
      /** Summary */
      summary: string;
    };
    /** MatchIn */
    MatchIn: {
      /**
       * Budget Iqd
       * @example 1500000
       */
      budget_iqd: number | string;
    };
    /** MatchOut */
    MatchOut: {
      /** Budget Iqd */
      budget_iqd: string;
      /** @description Read from the account, not the request */
      risk_profile: components['schemas']['RiskProfile'] | null;
      /**
       * Engine
       * @enum {string}
       */
      engine: 'rules' | 'llm';
      /** Message */
      message: string;
      /** Results */
      results: components['schemas']['MatchResult'][];
    };
    /** MatchResult */
    MatchResult: {
      /** Rank */
      rank: number;
      listing: components['schemas']['ListingOut'];
      /** Suggested Weight Grams */
      suggested_weight_grams: string;
      /** Execution Price Per Gram */
      execution_price_per_gram: string;
      /**
       * Estimated Total Iqd
       * @description Principal + commission for the suggestion
       */
      estimated_total_iqd: string;
      /** Commission Rate */
      commission_rate: string;
      /** Budget Usage Pct */
      budget_usage_pct: string;
      /** Score */
      score: string;
      /** Reason */
      reason: string;
    };
    /** OwnershipOut */
    OwnershipOut: {
      /**
       * Investor Id
       * Format: uuid
       */
      investor_id: string;
      /** Total Accumulated Grams */
      total_accumulated_grams: string;
      /**
       * Verified
       * @description Signature checked on this request
       */
      verified: boolean;
      /** Digital Signature Token */
      digital_signature_token: string | null;
      /** Updated At */
      updated_at: string | null;
      /**
       * Message
       * @description Shown when the investor owns nothing
       */
      message?: string | null;
      /**
       * Disclaimer
       * @default التوقيع الرقمي إثبات تقني داخلي لسلامة رصيدك داخل منصة صِلة، وليس سند ملكية قانونياً معترفاً به رسمياً.
       */
      disclaimer: string;
    };
    /** OwnershipSummary */
    OwnershipSummary: {
      /** Total Accumulated Grams */
      total_accumulated_grams: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** Page[ListingOut] */
    Page_ListingOut_: {
      /** Items */
      items: components['schemas']['ListingOut'][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** Page[TransactionOut] */
    Page_TransactionOut_: {
      /** Items */
      items: components['schemas']['TransactionOut'][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** PaymentOut */
    PaymentOut: {
      /** Status */
      status: string;
      /**
       * Payment Ref
       * Format: uuid
       */
      payment_ref: string;
      /** Amount Iqd */
      amount_iqd: string;
      /** Purpose */
      purpose: string;
    };
    /** PortfolioPerformance */
    PortfolioPerformance: {
      /** Total Grams */
      total_grams: string;
      /**
       * Total Paid Iqd
       * @description Sum of total_paid_by_investor
       */
      total_paid_iqd: string;
      /**
       * Current Value Iqd
       * @description Grams × today's price for each karat
       */
      current_value_iqd: string;
      /** Unrealized Pnl Iqd */
      unrealized_pnl_iqd: string;
      /** Unrealized Pnl Pct */
      unrealized_pnl_pct: string | null;
      /** Transactions Count */
      transactions_count: number;
      /** By Karat */
      by_karat: components['schemas']['KaratHolding'][];
    };
    /** PreviewIn */
    PreviewIn: {
      /**
       * Asset Id
       * Format: uuid
       */
      asset_id: string;
      /**
       * Purchased Weight Grams
       * @example 84.250
       */
      purchased_weight_grams: number | string;
    };
    /** PreviewOut */
    PreviewOut: {
      /**
       * Asset Id
       * Format: uuid
       */
      asset_id: string;
      /** Karat */
      karat: number;
      /** Purchased Weight Grams */
      purchased_weight_grams: string;
      /** Execution Price Per Gram */
      execution_price_per_gram: string;
      /**
       * Principal Amount
       * @description What the seller receives in full
       */
      principal_amount: string;
      /** Commission Rate */
      commission_rate: string;
      /** Commission Amount */
      commission_amount: string;
      /** Total Paid By Investor */
      total_paid_by_investor: string;
      /**
       * Price Updated At
       * Format: date-time
       * @description Timestamp of the market price used
       */
      price_updated_at: string;
      /**
       * Quoted At
       * Format: date-time
       */
      quoted_at: string;
      /**
       * Quote Expires At
       * Format: date-time
       */
      quote_expires_at: string;
      /**
       * Quote Token
       * @description Send back to /confirm before quote_expires_at
       */
      quote_token: string;
      risk_insight: components['schemas']['RiskInsightOut'] | null;
      /**
       * Risk Insight Note
       * @description Shown instead of the insight when AI analysis is unavailable
       */
      risk_insight_note?: string | null;
    };
    /** PriceHistoryOut */
    PriceHistoryOut: {
      /** Karat */
      karat: number;
      /**
       * Range
       * @enum {string}
       */
      range: '1D' | '1W' | '1M' | '3M' | '1Y';
      /**
       * Currency
       * @default IQD
       */
      currency: string;
      /** Points */
      points: components['schemas']['PricePoint'][];
    };
    /** PricePoint */
    PricePoint: {
      /**
       * Ts
       * Format: date-time
       */
      ts: string;
      /** Price Per Gram */
      price_per_gram: string;
    };
    /** PromoteOut */
    PromoteOut: {
      listing: components['schemas']['ListingOut'];
      payment: components['schemas']['PaymentOut'];
    };
    /** PublicConfigOut */
    PublicConfigOut: {
      /** Currency */
      currency: string;
      /** Supported Karats */
      supported_karats: number[];
      /** Commission Tiers */
      commission_tiers: components['schemas']['CommissionTier'][];
      /** Promotion Fee Iqd */
      promotion_fee_iqd: string;
      /** Promotion Duration Days */
      promotion_duration_days: number;
      /** Subscription Price Iqd */
      subscription_price_iqd: string;
      /** Subscription Duration Days */
      subscription_duration_days: number;
      /** Quote Ttl Seconds */
      quote_ttl_seconds: number;
    };
    /** RefreshIn */
    RefreshIn: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** RiskAnalysisIn */
    RiskAnalysisIn: {
      /**
       * Asset Id
       * Format: uuid
       */
      asset_id: string;
      /**
       * Weight Grams
       * @description Same meaning as purchased_weight_grams
       * @example 84.250
       */
      weight_grams: number | string;
    };
    /** RiskAnalysisOut */
    RiskAnalysisOut: {
      /**
       * Level
       * @enum {string}
       */
      level: 'low' | 'medium' | 'high';
      /** Insight */
      insight: string;
      /** Signals */
      signals: string[];
      /**
       * Engine
       * @enum {string}
       */
      engine: 'rules' | 'llm';
      /**
       * Asset Id
       * Format: uuid
       */
      asset_id: string;
      /** Purchased Weight Grams */
      purchased_weight_grams: string;
    };
    /** RiskInsightOut */
    RiskInsightOut: {
      /**
       * Level
       * @enum {string}
       */
      level: 'low' | 'medium' | 'high';
      /** Insight */
      insight: string;
      /** Signals */
      signals: string[];
      /**
       * Engine
       * @enum {string}
       */
      engine: 'rules' | 'llm';
    };
    /**
     * RiskProfile
     * @enum {string}
     */
    RiskProfile: 'low' | 'medium' | 'high';
    /** SignupIn */
    SignupIn: {
      role: components['schemas']['UserRole'];
      /**
       * Full Name
       * @example زينب الموسوي
       */
      full_name: string;
      /**
       * Email
       * Format: email
       * @example zainab@example.iq
       */
      email: string;
      /**
       * Password
       * @example Sila@2026
       */
      password: string;
      /** @description Required for investors; ignored for sellers. */
      risk_profile?: components['schemas']['RiskProfile'] | null;
    };
    /** SubscribeOut */
    SubscribeOut: {
      subscription_tier: components['schemas']['SubscriptionTier'];
      /** Subscription Expiry Date */
      subscription_expiry_date: string | null;
      /** Is Active */
      is_active: boolean;
      /** Days Remaining */
      days_remaining: number;
      /** Price Iqd */
      price_iqd: string;
      /** Duration Days */
      duration_days: number;
      payment: components['schemas']['PaymentOut'];
    };
    /** SubscriptionStatusOut */
    SubscriptionStatusOut: {
      subscription_tier: components['schemas']['SubscriptionTier'];
      /** Subscription Expiry Date */
      subscription_expiry_date: string | null;
      /** Is Active */
      is_active: boolean;
      /** Days Remaining */
      days_remaining: number;
      /** Price Iqd */
      price_iqd: string;
      /** Duration Days */
      duration_days: number;
    };
    /**
     * SubscriptionTier
     * @enum {string}
     */
    SubscriptionTier: 'free' | 'premium';
    /** TokenOut */
    TokenOut: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      /**
       * Expires In
       * @description Access token lifetime in seconds
       */
      expires_in: number;
    };
    /** TransactionOut */
    TransactionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Asset Id
       * Format: uuid
       */
      asset_id: string;
      /** Karat */
      karat: number;
      /** Seller Name */
      seller_name: string;
      /**
       * Buyer Ref
       * @description Anonymized buyer (seller view only)
       */
      buyer_ref: string | null;
      /** Purchased Weight Grams */
      purchased_weight_grams: string;
      /** Execution Price Per Gram */
      execution_price_per_gram: string;
      /** Principal Amount */
      principal_amount: string;
      /** Commission Rate */
      commission_rate: string;
      /** Commission Amount */
      commission_amount: string;
      /** Total Paid By Investor */
      total_paid_by_investor: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      role: components['schemas']['UserRole'];
      /** Full Name */
      full_name: string;
      /** Email */
      email: string;
      /** Kyc Verified */
      kyc_verified: boolean;
      risk_profile: components['schemas']['RiskProfile'] | null;
      subscription_tier: components['schemas']['SubscriptionTier'];
      /** Subscription Expiry Date */
      subscription_expiry_date: string | null;
      /**
       * Is Premium Active
       * @description subscription_expiry_date > now(); use this, not subscription_tier, to gate UI
       */
      is_premium_active: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: 'investor' | 'seller';
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  signup_api_auth_signup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Error */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  refresh_api_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  me_api_users_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  kyc_verify_investor_api_kyc_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KycOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  kyc_verify_seller_api_kyc_seller_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KycOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  prices_api_market_prices_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MarketPricesOut'];
        };
      };
      /** @description Error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  price_history_api_market_prices_history_get: {
    parameters: {
      query?: {
        karat?: number;
        range?: '1D' | '1W' | '1M' | '3M' | '1Y';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PriceHistoryOut'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  browse_listings_api_listings_get: {
    parameters: {
      query?: {
        karat?: number | null;
        /** @description Min base_price_per_gram */
        min_price?: number | string | null;
        /** @description Max base_price_per_gram */
        max_price?: number | string | null;
        sort?: 'promoted_first' | 'newest' | 'price_asc' | 'price_desc';
        /** @description "me" (seller auth) or a seller UUID */
        seller_id?: string | null;
        /** @description Only with seller_id=me */
        status?: components['schemas']['ListingStatus'] | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_ListingOut_'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_listing_api_listings_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Optional. Retrying with the same key returns the original result. */
        'Idempotency-Key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ListingCreateIn'];
      };
    };
    responses: {
      /** @description Idempotent replay */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListingOut'];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListingOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_listing_api_listings__listing_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListingOut'];
        };
      };
      /** @description Error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  update_listing_api_listings__listing_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ListingStatusIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListingOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  promote_listing_api_listings__listing_id__promote_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listing_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PromoteOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      402: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  smart_match_api_ai_match_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MatchIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MatchOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  risk_analysis_api_ai_risk_analysis_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RiskAnalysisIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RiskAnalysisOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  premium_insights_api_ai_insights_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InsightsOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  preview_api_transactions_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PreviewIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreviewOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  confirm_api_transactions_confirm_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Recommended. A repeated key returns the original transaction. */
        'Idempotency-Key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmIn'];
      };
    };
    responses: {
      /** @description Idempotent replay: the original transaction */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfirmOut'];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConfirmOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_transactions_api_transactions_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_TransactionOut_'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_transaction_api_transactions__transaction_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transaction_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  subscribe_api_subscription_subscribe_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubscribeOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      402: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  subscription_status_api_subscription_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubscriptionStatusOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  my_ownership_api_ownership_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OwnershipOut'];
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthOut'];
        };
      };
    };
  };
  public_config_api_config_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicConfigOut'];
        };
      };
    };
  };
}
